// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNJBnx0NbG7V115fjR_vlrPcCFZWsvA4',
    appId: '1:321654370224:android:ffeb9c165b3a400a8c3075',
    messagingSenderId: '321654370224',
    projectId: 'projeto-avaliativo-c9ee3',
    storageBucket: 'projeto-avaliativo-c9ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xYo2Fq2xJAC6a5ORPejQqUa9_Ltp-5Y',
    appId: '1:321654370224:ios:619c02bbac1e24d28c3075',
    messagingSenderId: '321654370224',
    projectId: 'projeto-avaliativo-c9ee3',
    storageBucket: 'projeto-avaliativo-c9ee3.appspot.com',
    iosClientId: '321654370224-61i72hcvr5tctdpi6ihdjqkgguslmp4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.profissaApp',
  );


}
